### ISSUE TITLE
How to release previously held payment?

### ISSUE THREAD

**Issue by paulchubatyy** [cloudipsp/python-sdk#4]
Hello team,

We're using your Python SDK and would like to understand how do we release previously held payment for the order?

Thanks

**Comment by has-well** [comment]
Hello, Paul, you can use https://github.com/cloudipsp/python-sdk/blob/master/cloudipsp/order.py#L30 method (example in test cases https://github.com/cloudipsp/python-sdk/blob/master/tests/order_tests.py#L44)
More info you can find in our documentation https://docs.fondy.eu/en/docs/page/12/

**Comment by paulchubatyy** [comment]
@has-well thanks for quick response.

The example code above explains how to capture the previously held transation. My question is regarding how do I release the hold back to the customer?

**Comment by paulchubatyy** [comment]
alright, I see how to reverse the order in the adjusdent test case. Thanks

**Comment by has-well** [comment]
Your welcome !
